build/adm-storage
blockchaintp/sawtooth-core pull request #21
Opened 2021-06-16 11:41 UTC by ryanbtp

This is probably worth PRing for discussion, though I still lack a green build mostly due to making my life difficult with Hipster Silicon

2021-06-16 11:56 UTC, ryanbtp commented on adm/src/config.rs
> +const DEFAULT_BLOCKSTORE_FILENAME_ROCKSDB: &str = "block-00.rocksdb";
The admin tool appears to have no options for the blockstore name, so this is just a convention based on paths from sawtooth env vars?

2021-06-16 11:57 UTC, ryanbtp commented on database/src/rocks_db.rs
> +        log::debug!("Flushing rocks db at {:?}", self.path);
Ok this is inconsistent, before I realised we were on 2018, will remove the namespace

2021-06-18 13:06 UTC, scealiontach requested changes
One trivial change requested, and just a question for my own edification.  Otherwise LGTM

2021-06-18 13:06 UTC, scealiontach commented on database/Cargo.toml
> +rocksdb = { version = ">=0.15.0", default-features = false, features = [ "lz4", "snappy", "zlib", "bzip2" ] }
need a newline here

2021-06-18 13:06 UTC, scealiontach commented on database/src/error.rs
> +    fn cause(&self) -> Option<&dyn std::error::Error> {
Why the dyn here? meaning I thought that was only for traits, and I thought Error was a concrete

2021-06-22 12:29 UTC, merged